# Generated by Django 3.1.1 on 2020-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
